// Auth action
export const START_AUTH = 'START_AUTH'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'

// COMPANIES 
export const START_COMPANIES = "START_COMPANIES";
export const COMPANIES_SUCCESS = "COMPANIES_SUCCESS";
export const COMPANIES_FAIL = "COMPANIES_FAIL";
export const DELETE_COMPANY_SUCCESS = "DELETE_COMPANY_SUCCESS";

// Users actions
export const START_USERS = "START_USERS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const USERS_FAIL = "USERS_FAIL";
