// Auth action
export const START_AUTH = 'START_AUTH'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'

export const START_TEACHER = "START_TEACHER";
export const TEACHER_SUCCESS = "TEACHER_SUCCESS";
export const TEACHER_FAIL = "TEACHER_FAIL";
export const ADD_TEACHER_SUCCESS = "ADD_TEACHER_SUCCESS";
export const DELETE_TEACHER_SUCCESS = "DELETE_TEACHER_SUCCESS";
export const UPDATE_TEACHER_SUCCESS = "UPDATE_TEACHER_SUCCESS";

export const START_STUDENT = "START_STUDENT";
export const STUDENT_SUCCESS = "STUDENT_SUCCESS";
export const STUDENT_FAIL = "STUDENT_FAIL";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";

export const START_COURSE          = "START_COURSE";
export const COURSE_FAIL           = "COURSE_FAIL";

export const COURSE_SUCCESS        = "COURSE_SUCCESS";        // fetch list
export const ADD_COURSE_SUCCESS    = "ADD_COURSE_SUCCESS";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";

export const START_LANGUAGE = "START_LANGUAGE";
export const LANGUAGE_FAIL = "LANGUAGE_FAIL";
export const LANGUAGE_SUCCESS = "LANGUAGE_SUCCESS";
export const ADD_LANGUAGE_SUCCESS = "ADD_LANGUAGE_SUCCESS";
export const DELETE_LANGUAGE_SUCCESS = "DELETE_LANGUAGE_SUCCESS";
export const UPDATE_LANGUAGE_SUCCESS = "UPDATE_LANGUAGE_SUCCESS";

export const START_COUNTRY = "START_COUNTRY";
export const COUNTRY_FAIL = "COUNTRY_FAIL";
export const COUNTRY_SUCCESS = "COUNTRY_SUCCESS";
export const ADD_COUNTRY_SUCCESS = "ADD_COUNTRY_SUCCESS";
export const DELETE_COUNTRY_SUCCESS = "DELETE_COUNTRY_SUCCESS";
export const UPDATE_COUNTRY_SUCCESS = "UPDATE_COUNTRY_SUCCESS";


export const START_COURSE_TEACHER = "START_COURSE_TEACHER";
export const COURSE_TEACHER_FAIL = "COURSE_TEACHER_FAIL";
export const COURSE_TEACHER_SUCCESS = "COURSE_TEACHER_SUCCESS";
export const ADD_COURSE_TEACHER_SUCCESS = "ADD_COURSE_TEACHER_SUCCESS";
export const DELETE_COURSE_TEACHER_SUCCESS = "DELETE_COURSE_TEACHER_SUCCESS";
export const UPDATE_COURSE_TEACHER_SUCCESS = "UPDATE_COURSE_TEACHER_SUCCESS";

export const FETCH_VIDEO_TEACHERS = "FETCH_VIDEO_TEACHERS";
export const ADD_VIDEO_TEACHER = "ADD_VIDEO_TEACHER";
export const UPDATE_VIDEO_TEACHER = "UPDATE_VIDEO_TEACHER";
export const DELETE_VIDEO_TEACHER = "DELETE_VIDEO_TEACHER";

export const START_VIDEO_TEACHER = "START_VIDEO_TEACHER";
export const VIDEO_TEACHER_FAIL = "VIDEO_TEACHER_FAIL";
export const VIDEO_TEACHER_SUCCESS = "VIDEO_TEACHER_SUCCESS";
export const ADD_VIDEO_TEACHER_SUCCESS = "ADD_VIDEO_TEACHER_SUCCESS";
export const DELETE_VIDEO_TEACHER_SUCCESS = "DELETE_VIDEO_TEACHER_SUCCESS";
export const UPDATE_VIDEO_TEACHER_SUCCESS = "UPDATE_VIDEO_TEACHER_SUCCESS";

export const START_CALL_LIST = "START_CALL_LIST";
export const CALL_LIST_SUCCESS = "CALL_LIST_SUCCESS";
export const CALL_LIST_FAIL = "CALL_LIST_FAIL";

// COMMUNITY
export const START_COMMUNITY = "START_COMMUNITY";
export const COMMUNITY_SUCCESS = "COMMUNITY_SUCCESS";
export const COMMUNITY_FAIL = "COMMUNITY_FAIL";

export const ADD_COMMUNITY_SUCCESS = "ADD_COMMUNITY_SUCCESS";
export const DELETE_COMMUNITY_SUCCESS = "DELETE_COMMUNITY_SUCCESS";
export const UPDATE_COMMUNITY_SUCCESS = "UPDATE_COMMUNITY_SUCCESS";

export const LIST_PENDING_REQUESTS_SUCCESS = "LIST_PENDING_REQUESTS_SUCCESS";
export const REJECT_MEMBERSHIP_SUCCESS = "REJECT_MEMBERSHIP_SUCCESS";

// Community action types
export const FETCH_COMMUNITIES = 'FETCH_COMMUNITIES';
export const ADD_COMMUNITY = 'ADD_COMMUNITY';
export const UPDATE_COMMUNITY = 'UPDATE_COMMUNITY';
export const DELETE_COMMUNITY = 'DELETE_COMMUNITY';
