export const PARTNER = 'partner';
export const COMPANY = 'company';
export const ADMIN = 'admin';
export const DRIVER = 'driver';
export const VALIDATE_NAME = /^[a-zA-Z ]*$/;
export const VALIDATE_JOB_NUMBER = /^[a-zA-Z0-9]+$/;
export const ALPHABATES_NUMERIC_SPECIAL = /^[ A-Za-z0-9_@./#&+-]*$/;
export const ALPHABATES_NUMERIC = /^[A-Za-z0-9 _]*[A-Za-z0-9][A-Za-z0-9 _]*$/;
export const ALPHABATES_NUMERIC_SPECIAL_CHARACTERS = /^[ A-Za-z0-9_@./#&+-]*$/;

export const VIN_REGEX = /^[A-HJ-NPR-Z0-9]{0,17}$/; 
export const USERNAME_REGEX = /^[A-Za-z0-9]{4,}$/; 
export const SERIAL_NUMBER_REGEX = /^[A-Za-z0-9]{1,12}$/;

export const VALIDATE_PASSWORD = /^(?=.*?[A-Z])(?=(.*[a-z]){1,})(?=(.*[\d]){1,})(?=(.*[\W]){1,})(?!.*\s).{8,64}$/;
export const NUMERIC_CHARACTERS = /^[0-9]+$/;
export const VALIDATE_PRICE = /^(?!(?:.*?\.){2})\d{0,3}[.]?\d{0,3}[.]?\d{0,3}[.]?\d{0,3}[.]?\d{0,3}[.]?\d{1,3}[,]?\d{0,2}$/;
export const VALIDATE_MAC_ADDRESS = /^(([A-Fa-f0-9]{2}[:]){5}[A-Fa-f0-9]{2}[,]?)+$/i;
export const VALIDATE_PHONE_NUMBER = /^((\\+[1-9]{1,4}[ \\-]*)|(\\([0-9]{2,3}\\)[ \\-]*)|([0-9]{2,4})[ \\-]*)*?[0-9]{3,4}?[ \\-]*[0-9]{3,4}?$/;
export const VALIDATE_US_PHONE_NUMBER = /^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$/im; // eslint-disable-line
export const VALIDATE_NUMBERS = /^[1-9]\d*$/
export const VALIDATE_DECIMAL = /^\d+\.\d{1,1}$/
export const VALIDATE_POSITIVE_NEGATIVE = /^-?\d*\d{0,6}$/
export const VALIDATE_NEGATIVE_POSITIVE_BUT_NOT_ZERO = /^\-?[1-9]\d*$/
export const SORTING ={
  COMPANY:"company",
  NAME:"name",
  ID:"id",
  DOT:"dot",
  ASC:"asc",
  DESC:"desc",
  VEHICLE:'vehicle',
  DRIVER:"driver",
  GROUP:"group"
}
export const FUELTYPE = [
{value: 'Diesel', label: 'Diesel'},
{value: 'Gasoline', label: 'Gasoline'},
{value: 'Propane', label: 'Propane'},
{value: 'Liquid Natural Gas', label: 'Liquid Natural Gas'},
{value: 'Compressed Natural Gas', label: 'Compressed Natural Gas'},
{value: 'Ethanol', label: 'Ethanol'},
{value: 'Methanol', label: 'Methanol'},
{value: 'E-85', label: 'E-85'},
{value: 'M-85', label: 'M-85'},
{value: 'A-55', label: 'A-55'},
{value: 'Biodiesel', label: 'Biodiesel'},
{value: 'Other', label: 'Other'}
]

export const MAKE =[ {value:"Freightliner",label:"Freightliner"},
{value:"Volvo",label:"Volvo"},
{value:"Ram",label:"Ram"},
{value:"International",label:"International"},
{value:"Kenworth",label:"Kenworth"},
{value:"Peterbilt",label:"Peterbilt"},
{value:"Mack",label:"Mack"},
{value:"Western Star",label:"Western Star"},
{value:"Ford",label:"Ford"},
{value:"GMC",label:"GMC"},
{value:"Wabash National Corporation",label:"Wabash National Corporation"},
{value:"Chevrolet",label:"Chevrolet"},
{value:"Mercedes",label:"Mercedes"},
{value:"HINO",label:"HINO"},
{value:"BIG TEX",label:"BIG TEX"},
{value:"KAUFMAN",label:"KAUFMAN"},
{value:"STERLING",label:"STERLING"},
{value:"(VNTC)",label:"(VNTC)"},
{value:"PJ",label:"PJ"} 
]
export const VEHICLE_MODEL_OPTIONS = [
    {value:"Cascadia",label:"Cascadia"},
    {value:"WFC 120",label:"WFC 120"},
    {value:"FLA",label:"FLA"},
    {value:"FLA 104",label:"FLA 104"},
    {value:"FLA 104 64",label:"FLA 104 64"},
    {value:"FLA 75",label:"FLA 75"},
    {value:" FLA 7542T",label:" FLA 7542T"},
    {value:"FLA 8662",label:"FLA 8662"},
    {value:"FLA 8664T",label:"FLA 8664T"},
    {value:"FLA 9664",label:"FLA 9664"},
    {value:"FLA 9664T",label:"FLA 9664T"},
    {value:"FLB",label:"FLB"},
    {value:"FLB 100 42T",label:"FLB 100 42T"},
    {value:"FLB 104 64",label:"FLB 104 64"},
    {value:"FLB 9664",label:"FLB 9664"},
    {value:"FLT",label:"FLT"},
    {value:"FLT 6442",label:"FLT 6442"},
    {value:"FLT 9664",label:"FLT 9664"},
    {value:"FLT 7564",label:"FLT 7564"},
    {value:"Argosy",label:"Argosy"},
    {value:"FLC",label:"FLC"},
    {value:"FLC 120",label:"FLC 120"},
    {value:"FLC 120 64",label:"FLC 120 64"},
    {value:"FLC 120 64 T",label:"FLC 120 64 T"},
    {value:"FLC 120 84",label:"FLC 120 84"},
    {value:"FLD",label:"FLD"},
    {value:"FLD 112",label:"FLD 112"},
    {value:"FLD 120 42 S",label:"FLD 120 42 S"},
    {value:"FLD 120 64 ST",label:"FLD 120 64 ST"},
    {value:"FLD 120 64 T",label:"FLD 120 64 T"},
    {value:"FLD 120 HD",label:"FLD 120 HD"},
    {value:"FLD 120 SD",label:"FLD 120 SD"},
    {value:"FLD 120 SFFA",label:"FLD 120 SFFA"},
    {value:"FLD 132 64T",label:"FLD 132 64T"},
    {value:"Classic XL",label:"Classic XL"},
    {value:"FLD-SD",label:"FLD-SD"},
    {value:"FLD 120",label:"FLD 120"},
    {value:"Classic",label:"Classic"},
    {value:"108SD AB",label:"108SD AB"},
    {value:"114SD AB",label:"114SD AB"},
    {value:"114SD AF",label:"114SD AF"},
    {value:"FLC 112",label:"FLC 112"},
    {value:"FLC 112 62 ST",label:"FLC 112 62 ST"},
    {value:"FL 50",label:"FL 50"},
    {value:"FL 60",label:"FL 60"},
    {value:"FL 70",label:"FL 70"},
    {value:"FL 80",label:"FL 80"},
    {value:"FL 106",label:"FL 106"},
    {value:"FL 112",label:"FL 112"},
    {value:"Condor",label:"Condor"},
    {value:"EconicSD",label:"EconicSD"},
    {value:"FC70",label:"FC70"},
    {value:"FC80",label:"FC80"},
    {value:"M2 106",label:"M2 106"},
    {value:"M2e Hybrid",label:"M2e Hybrid"},
    {value:"M2 112",label:"M2 112"},
    {value:"M2 106V",label:"M2 106V"},
    {value:"M2 112V",label:"M2 112V"},
    {value:"MT-45",label:"MT-45"},
    {value:"MT-55",label:"MT-55"},
    {value:"MT50e",label:"MT50e"},
    {value:"Freightliner Sprinter",label:"Freightliner Sprinter"},
    {value:"FS-65",label:"FS-65"},
    {value:"S2",label:"S2"},
    {value:"C2",label:"C2"},
    {value:"WFT",label:"WFT"},
    {value:"Century Class",label:"Century Class"},
    {value:"Coronado",label:"Coronado"},
    {value:"New Cascadia",label:"New Cascadia"},
    {value:"eCascadia",label:"eCascadia"},
    {value:"VNL",label:"VNL"},
    {value:"FL6",label:"FL6"},
    {value:"FE",label:"FE"},
    {value:"FM9",label:"FM9"},
    {value:"FH12",label:"FH12"},
    {value:"FH16",label:"FH16"},
    {value:"FMX",label:"FMX"},
    {value:"VHD",label:"VHD"},
    {value:"VNM",label:"VNM"},
    {value:"VNR",label:"VNR"},
    {value:"VNX",label:"VNX"},
    {value:"VM",label:"VM"},
    {value:"NH",label:"NH"},
    {value:"FM12",label:"FM12"},
    {value:"VT",label:"VT"},
    {value:"FLC",label:"FLC"},
    {value:"FM7",label:"FM7"},
    {value:"FM10",label:"FM10"},
    {value:"2500",label:"2500"},
    {value:"3500",label:"3500"},
    {value:"4000",label:"4000"},
    {value:"4300",label:"4300"},
    {value:"7000",label:"7000"},
    {value:"7500",label:"7500"},
    {value:"8000",label:"8000"},
    {value:"9000",label:"9000"},
    {value:"LT",label:"LT"},
    {value:"ProStar",label:"ProStar"},
    {value:"9900ix",label:"9900ix"},
    {value:"RH",label:"RH"},
    {value:"HX",label:"HX"},
    {value:"HV",label:"HV"},
    {value:"MV",label:"MV"},
    {value:"CV",label:"CV"},
    {value:"LoneStar",label:"LoneStar"},
    {value:"5000i",label:"5000i"},
    {value:"W900",label:"W900"},
    {value:"W990",label:"W990"},
    {value:"T800",label:"T800"},
    {value:"T880",label:"T880"},
    {value:"T680",label:"T680"},
    {value:"T380",label:"T380"},
    {value:"T480",label:"T480"},
    {value:"T180",label:"T180"},
    {value:"T280",label:"T280"},
    {value:"T2000",label:"T2000"},
    {value:"T700",label:"T700"},
    {value:"T660",label:"T660"},
    {value:"T600",label:"T600"},
    {value:"T400",label:"T400"},
    {value:"T450",label:"T450"},
    {value:"T440",label:"T440"},
    {value:"T470",label:"T470"},
    {value:"T170",label:"T170"},
    {value:"T270",label:"T270"},
    {value:"T370",label:"T370"},
    {value:"K270",label:"K270"},
    {value:"K370",label:"K370"},
    {value:"K360",label:"K360"},
    {value:"K260",label:"K260"},
    {value:"K300",label:"K300"},
    {value:"K100",label:"K100"},
    {value:"200",label:"200"},
    {value:"210",label:"210"},
    {value:"220",label:"220"},
    {value:"320",label:"320"},
    {value:"325",label:"325"},
    {value:"330",label:"330"},
    {value:"335",label:"335"},
    {value:"337",label:"337"},
    {value:"340",label:"340"},
    {value:"348",label:"348"},
    {value:"349",label:"349"},
    {value:"357",label:"357"},
    {value:"362",label:"362"},
    {value:"365",label:"365"},
    {value:"367",label:"367"},
    {value:"372",label:"372"},
    {value:"375",label:"375"},
    {value:"377",label:"377"},
    {value:"378",label:"378"},
    {value:"379",label:"379"},
    {value:"384",label:"384"},
    {value:"385",label:"385"},
    {value:"386",label:"386"},
    {value:"387",label:"387"},
    {value:"388",label:"388"},
    {value:"389",label:"389"},
    {value:"397",label:"397"},
    {value:"520",label:"520"},
    {value:"535",label:"535"},
    {value:"536",label:"536"},
    {value:"537",label:"537"},
    {value:"548",label:"548"},
    {value:"567",label:"567"},
    {value:"579",label:"579"},
    {value:"587",label:"587"},
    {value:"389K",label:"389K"},
    {value:"379x",label:"379x"},
    {value:"Pinnacle",label:"Pinnacle"},
    {value:"Anthem",label:"Anthem"},
    {value:"Granite",label:"Granite"},
    {value:"Granite Axle Back",label:"Granite Axle Back"},
    {value:"TerraPro Cabover",label:"TerraPro Cabover"},
    {value:"Anthem Axle Back",label:"Anthem Axle Back"},
    {value:"Pinnacle Axle Forward",label:"Pinnacle Axle Forward"},
    {value:"Pinnacle DayCab",label:"Pinnacle DayCab"},
    {value:"Pinnacle Sleeper",label:"Pinnacle Sleeper"},
    {value:"Pinnacle Rawhide",label:"Pinnacle Rawhide"},
    {value:"Smartway",label:"Smartway"},
    {value:"LR",label:"LR"},
    {value:"TerraPro Low Entry",label:"TerraPro Low Entry"},
    {value:"Kerax 8 x 8",label:"Kerax 8 x 8"},
    {value:"Metro-Liner",label:"Metro-Liner"},
    {value:"Super-Liner",label:"Super-Liner"},
    {value:"Titan",label:"Titan"},
    {value:"Trident",label:"Trident"},
    {value:"Trident Axle Forward",label:"Trident Axle Forward"},
    {value:"Trident Axle Back",label:"Trident Axle Back"},
    {value:"4700",label:"4700"},
    {value:"4800",label:"4800"},
    {value:"4900",label:"4900"},
    {value:"6900",label:"6900"},
    {value:"X-series",label:"X-series"},
    {value:"5700XE",label:"5700XE"},
    {value:"F-350",label:"F-350"},
    {value:"F-750",label:"F-750"},
    {value:"Sierra HD",label:"Sierra HD"},
    {value:"TT",label:"TT"},
    {value:"TR",label:"TR"},
    {value:"Wabash National Corporation",label:"Wabash National Corporation"},
    {value:"Silverado 2500HD",label:"Silverado 2500HD"},
    {value:"Columbia",label:"Columbia"},
    {value:"MA025",label:"MA025"},
    {value:"4500",label:"4500"},
    {value:"LF687",label:"LF687"},
    {value:"T300",label:"T300"},
    {value:"150",label:"150"},
    {value:"F-150",label:"F-150"},
    {value:"310",label:"310"},
    {value:"Cascadia 125",label:"Cascadia 125"},
    {value:"CST120",label:"CST120"},
    {value:"CXU",label:"CXU"},
    {value:"LT625",label:"LT625"},
    {value:"F-650",label:"F-650"},
    {value:"M2",label:"M2"},
    {value:"LF677",label:"LF677"},
    {value:"L9427",label:"L9427"},
    {value:"W9 Series",label:"W9 Series"},
    {value:"Sprinter",label:"Sprinter"},
    {value:"49 x Chassis",label:"49 x Chassis"},
    {value:"Conventional",label:"Conventional"},
    {value:"5500",label:"5500"},
    {value:"5700",label:"5700"},
    {value:"Big Tex",label:"Big Tex"},
    {value:"250",label:"250"},
    {value:"MD",label:"MD"},
    {value:"MV607",label:"MV607"},
    {value:"C34",label:"C34"},
    {value:"F-450",label:"F-450"},
    {value:"F350SD",label:"F350SD"},
    {value:"L9500 series",label:"L9500 series"},
    {value:"Cascadia 126",label:"Cascadia 126"},
    {value:"Silverado HD",label:"Silverado HD"},
    {value:"(VNTC)",label:"(VNTC)"},
    {value:"PJ",label:"PJ"},
    {value:"4200",label:"4200"},
    {value:"57X Chassis",label:"57X Chassis"}
  ];
export const ROLE = [
{value:"company-administrator",label:"Company Administrator"},
{value:"company-portal-user",label:"Company Safety Personal"},
{value:"company-fleet-manager",label:"Company Fleet Manager"},
{value:"company-broker",label:"Broker"}]

export const VEHICLE_STATUS = [
  {value: '', label: 'All'},
  {value: 'Vehicle Condition Satisfactory', label: 'Vehicle Condition Satisfactory'},
  {value: 'Defects Not Corrected', label: 'Defects Not Corrected'},
  {value: 'Defects Corrected', label: 'Defects Corrected'}
]

export const ELD_STATUS = [
    {value: '', label: 'All'},
    {value: true, label: 'Connected'},
    {value: false, label: 'Disconnected'},
] 

export const VIOLATION_STATUS = [
  {value: '', label: 'All'},
  {value: 'compliant_drivers', label: 'Compliant Drivers'},
  {value: 'violation_n_errors', label: 'Violation & Errors'},
]

export const TRUCK_STATUS = [
  {value: '', label: 'All'},
  {value: 'IN_MOTION', label: 'In Motion'},
  {value: 'DS_OFF', label: 'Off Duty'},
  {value: 'DS_ON', label: 'On Duty'},
  {value: 'DS_SB', label: 'Sleep'},

]
export const SORT_STATUS = [
  {value: '1', label: 'Ascending'},
  {value: '-1', label: 'Descending'},
]